skillMetadata:
  sections:
    - name: Weather API
      fields:
        - name: api_key
          type: text
          label: OpenWeatherMap API Key
          value:
    - name: Preferences
      fields:
        - name: units
          type: select
          label: Temperature units
          options: Default (from Basic Settings)|default;Celsius|celsius;Farenheit|farenheit
          value: default